name: mentai
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  #camera: ^0.10.0+4
  camera:
    git:
      url: https://github.com/flutter/plugins
      path: packages/camera/camera
      ref: 9e46048ad2e1f085c1e8f6c77391fa52025e681f
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.2
  d_chart: ^0.1.0
  flutter:
    sdk: flutter
  flutter_login: ^4.1.0
  flutter_native_image: ^0.0.6+1
  get: ^4.6.5
  google_fonts: ^3.0.1
  introduction_screen: ^3.0.2
  lottie: ^1.4.3
  persistent_bottom_nav_bar: ^5.0.2
  #mojo_perception: ^2.0.0
  tflite:
    git:
      url: https://github.com/zhengbomo/flutter_tflite.git

dev_dependencies:
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/Images/
    - assets/Animations/
    - assets/AiModel/
